import { expect, test } from "vitest";
import { gzipSync } from "node:zlib";
import { inspectSourceDocument } from "../source-document-inspection.js";
import { parseSourceDocument } from "../parsers/source-document.js";
import { decodeSourceBytes } from "../gogols/parse-sources-report.js";

const root = "www.stadtbranchenbuch.com";
const robots = `${root}/city.stadtbranchenbuch.com/robots.txt`;
test("control bytes do not form a valid robots policy", () => {
  expect(
    inspectSourceDocument(robots, Buffer.from("User-agent: *\u0000\nDisallow: /\n")).inspection
      .kind,
  ).toBe("robots-unavailable");
});
test("blank cache inventory is not a recognized metadata inventory", () => {
  expect(
    inspectSourceDocument(`${root}/hts-cache/new.lst`, Buffer.from("\n\n")).inspection.kind,
  ).toBe("other");
});
test.each([
  [
    "hts-log.txt",
    "HTTrack3.49-2 launched on Sun, 19 Apr 2026 23:13:06 at https://www.stadtbranchenbuch.com/",
  ],
  ["hts-cache/readme.txt", "What's in this folder?\nThis folder has been generated by WinHTTrack"],
  ["hts-cache/new.lst", "[city.stadtbranchenbuch.com/123.html]\n"],
  ["hts-cache/doit.log", "-qi\nHTTrack Website Copier/3.x"],
  ["hts-cache/winprofile.ini", "Near=0\nHTMLFirst=1\nCache=1\n"],
])("mirror metadata %s needs both a content signature and exact placement", (file, content) => {
  expect(inspectSourceDocument(`${root}/${file}`, Buffer.from(content)).inspection.kind).toBe(
    "mirror-metadata",
  );
  expect(
    inspectSourceDocument(`${root}/${file}`, Buffer.from("unknown content")).inspection.kind,
  ).toBe("other");
  expect(
    inspectSourceDocument(`${root}/external.example/${file}`, Buffer.from(content)).inspection.kind,
  ).toBe("other");
});
test.each([`${root}/favicon.ico.html`, "firmenabc.com/empty.csv"])(
  "shared harvest entry refuses empty source %s",
  (file) => {
    expect(parseSourceDocument(file, "")).toMatchObject({
      disposition: "unrecognized",
      result: { items: [], warnings: ["empty-capture"] },
    });
  },
);
test("gzip robots remain a retained policy document, never capture permission", () => {
  const result = inspectSourceDocument(robots, gzipSync("User-agent: *\nDisallow: /\n"));
  expect(result.inspection).toMatchObject({
    kind: "robots-policy",
    encoding: "gzip",
    decodedBytes: 26,
  });
  expect(result.payload.toString()).toBe("User-agent: *\nDisallow: /\n");
});
test.each([
  "<html>Denied</html>",
  "<Error><Code>AccessDenied</Code></Error>",
  "not a robots policy",
])("unexpected robots body stays unavailable: %s", (content) => {
  expect(inspectSourceDocument(robots, Buffer.from(content)).inspection.kind).toBe(
    "robots-unavailable",
  );
});
test.each([
  robots,
  `${root}/city.stadtbranchenbuch.com/123.html`,
  `${root}/external.example/file.shtml`,
  `${root}/image.png`,
])("empty capture remains explicit for %s", (file) => {
  expect(inspectSourceDocument(file, Buffer.alloc(0)).inspection.kind).toBe("empty-capture");
});
test("a named robots file containing HTML company evidence is not ignored", () => {
  expect(
    inspectSourceDocument(robots, Buffer.from('<html><input name="eintragId" value="123"></html>'))
      .inspection.kind,
  ).toBe("robots-unavailable");
});
test("classifies extensionless external HTML without admitting a catalog company", () => {
  expect(
    inspectSourceDocument(
      `${root}/external.example/store`,
      Buffer.from("<!doctype html><html><h1>Shop</h1></html>"),
    ).inspection.kind,
  ).toBe("external-html");
});
test("gzip decoding validates payload integrity and forbids nesting", () => {
  const valid = gzipSync("User-agent: *\nDisallow: /\n");
  expect(() => inspectSourceDocument(robots, valid.subarray(0, valid.length - 3))).toThrow(
    "SOURCE_GZIP_INVALID_OR_OVERSIZED",
  );
  expect(() => inspectSourceDocument(robots, gzipSync(valid))).toThrow("SOURCE_NESTED_COMPRESSION");
});
test("compressed expansion cannot exceed the source byte limit", () => {
  expect(() => inspectSourceDocument(robots, gzipSync("x".repeat(8 * 1024 * 1024 + 1)))).toThrow(
    "SOURCE_GZIP_INVALID_OR_OVERSIZED",
  );
});
test("harvest's decoder uses the same validated gzip payload", () => {
  expect(decodeSourceBytes(gzipSync('<meta charset="utf-8">Gründe'), ".html")).toContain("Gründe");
});
test("cookie metadata is identified without returning its values", () => {
  const { inspection } = inspectSourceDocument(
    `${root}/cookies.txt`,
    Buffer.from("# HTTrack Website Copier Cookie File\nprivate-cookie-value"),
  );
  expect(inspection.kind).toBe("sensitive-cookie-jar");
  expect(JSON.stringify(inspection)).not.toContain("private-cookie-value");
  expect(
    inspectSourceDocument(
      `${root}/external.example/cookies.txt`,
      Buffer.from("# HTTrack Website Copier Cookie File\nprivate-cookie-value"),
    ).inspection.kind,
  ).toBe("other");
});
test("retained mirror dates are hints, not a substituted Q3 observation timestamp", () => {
  const { inspection } = inspectSourceDocument(
    `${root}/city.stadtbranchenbuch.com/123.html`,
    Buffer.from(
      "<html><!-- Mirrored from city.stadtbranchenbuch.com/123.html by HTTrack Website Copier/3.x [XR&CO\x272014], Sun, 19 Apr 2026 21:14:17 GMT --></html>",
    ),
  );
  expect(inspection.mirrorTimestampHints).toEqual(["Sun, 19 Apr 2026 21:14:17 GMT"]);
  expect(inspection).not.toHaveProperty("measuredAt");
});
const legal =
  '<title>Datenschutz</title><h1>Datenschutzerklärung Stadtbranchenbuch.com / Stand 25.05.2018</h1><link rel="canonical" href=""><meta property="og:url" content=""><script type="application/ld+json">{"@type":"WebSite"}</script>';
test("recognizes the actual legal page shape without relaxing business metadata checks", () => {
  const file = `${root}/${root}/content/datenschutz.html`;
  expect(parseSourceDocument(file, legal)).toMatchObject({
    disposition: "ignored",
    result: { parserKind: "sbb-legal-ignored", items: [] },
  });
  expect(() => parseSourceDocument(file, legal + '<input name="eintragId" value="123">')).toThrow();
  expect(() => parseSourceDocument(file, legal.replace('"WebSite"', '"LocalBusiness"'))).toThrow();
  expect(() =>
    parseSourceDocument(
      file,
      legal.replace('"WebSite"', '"WebSite","@graph":[{"@type":"LocalBusiness"}]'),
    ),
  ).toThrow();
  expect(() => parseSourceDocument(`${root}/123.html`, legal)).toThrow();
});
test("recognizes a generated mirror index only with its content signature", () => {
  const file = `${root}/index.html`;
  const html =
    '<meta name="generator" content="HTTrack Website Copier/3.x"><h1>Index of locally available sites:</h1>';
  expect(parseSourceDocument(file, html).disposition).toBe("ignored");
  expect(parseSourceDocument(file, "<h1>Other content</h1>").disposition).toBe("unrecognized");
});
