/*
<MODULE_CONTRACT>
  <purpose>Classify retained mirror bytes without promoting external pages or metadata into business evidence.</purpose>
  <non-goals><item>Does not infer capture authority, authorize robots access or expose cookie contents.</item></non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY><item>Distinguish bounded gzip payloads, empty captures, policies, sensitive metadata and external HTML.</item></CHANGE_SUMMARY>
*/
// @ai-invariant: Timestamp hints are untrusted source text, never a measurement time or quarterly authority.
import path from "node:path";
import { createHash } from "node:crypto";
import { decodeSourceBytes, decodeSourcePayload } from "./gogols/parse-sources-report.js";
import { isStadtbranchenbuchHost } from "./parsers/StadtbranchenbuchMirrorParser.js";

export interface SourceDocumentInspection {
  kind:
    | "empty-capture"
    | "robots-policy"
    | "robots-unavailable"
    | "mirror-metadata"
    | "sensitive-cookie-jar"
    | "catalog-html"
    | "external-html"
    | "html"
    | "other";
  encoding: "identity" | "gzip";
  decodedBytes: number;
  decodedSha256: string;
  mirrorTimestampHints: string[];
}

function mirrorHints(content: string): string[] {
  const hints = new Set<string>();
  let cursor = 0;
  for (;;) {
    const start = content.indexOf("<!--", cursor);
    if (start < 0) break;
    const end = content.indexOf("-->", start + 4);
    if (end < 0) break;
    cursor = end + 3;
    if (end - start > 4096) continue;
    const comment = content.slice(start + 4, end).trim();
    if (!comment.startsWith("Mirrored from ") || !comment.includes(" by HTTrack ")) continue;
    const hint = comment.match(
      /, ([A-Za-z]{3}, [0-9]{1,2} [A-Za-z]{3} [0-9]{4} [0-9:]{8} GMT)$/,
    )?.[1];
    if (hint) hints.add(hint);
  }
  return [...hints].sort();
}

export function inspectSourceDocument(
  logicalPath: string,
  raw: Buffer,
): { inspection: SourceDocumentInspection; payload: Buffer } {
  const payload = decodeSourcePayload(raw);
  const inspection: SourceDocumentInspection = {
    kind: payload.length === 0 ? "empty-capture" : "other",
    encoding: raw[0] === 0x1f && raw[1] === 0x8b ? "gzip" : "identity",
    decodedBytes: payload.length,
    decodedSha256: createHash("sha256").update(payload).digest("hex"),
    mirrorTimestampHints: [],
  };
  if (!payload.length) return { inspection, payload };
  const parts = logicalPath.replace(/\\/g, "/").split("/");
  const file = parts.at(-1)!;
  const mirror = isStadtbranchenbuchHost(parts[0]!);
  const deepestHost = parts
    .slice(0, -1)
    .filter((part) => part.includes("."))
    .at(-1);
  const html = /<(?:!doctype\s+html|html|head|body)\b/i.test(
    payload.subarray(0, 2048).toString("latin1"),
  );
  if (html) {
    inspection.kind = mirror
      ? deepestHost && isStadtbranchenbuchHost(deepestHost)
        ? "catalog-html"
        : "external-html"
      : "html";
    const content = decodeSourceBytes(payload, ".html");
    inspection.mirrorTimestampHints = mirrorHints(content);
  }
  if (file === "robots.txt") {
    const content = decodeSourceBytes(payload, html ? ".html" : ".txt");
    const lines = content
      .split(/\r?\n/)
      .map((line) => line.replace(/#.*$/, "").trim())
      .filter(Boolean);
    const valid =
      !html &&
      !/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(content) &&
      lines.some((line) => /^user-agent:\s*\S+/i.test(line)) &&
      lines.every((line) =>
        /^(?:user-agent|disallow|allow|sitemap|crawl-delay|host):[^<>]*$/i.test(line),
      );
    inspection.kind = valid ? "robots-policy" : "robots-unavailable";
  }
  // Metadata classification needs both exact mirror placement and a format signature.
  // Cookie jars remain quarantined: identifying the format does not authorize its export.
  if (mirror && (parts.length === 2 || (parts.length === 3 && parts[1] === "hts-cache")) && !html) {
    const content = decodeSourceBytes(payload, path.extname(file));
    if (
      parts.length === 2 &&
      file === "cookies.txt" &&
      content.startsWith("# HTTrack Website Copier Cookie File")
    )
      inspection.kind = "sensitive-cookie-jar";
    const metadata =
      (parts.length === 2 &&
        file === "hts-log.txt" &&
        /^HTTrack[^\r\n]+ launched on /.test(content)) ||
      (parts[1] === "hts-cache" &&
        ((file === "readme.txt" &&
          content.startsWith("What's in this folder?") &&
          content.includes("has been generated by WinHTTrack")) ||
          (file === "new.lst" &&
            content.trim().length > 0 &&
            content
              .split(/\r?\n/)
              .filter(Boolean)
              .every((line) => /^\[[^\]\r\n]+\]$/.test(line))) ||
          (file === "doit.log" &&
            content.startsWith("-qi") &&
            content.includes("HTTrack Website Copier/3.x")) ||
          (file === "winprofile.ini" &&
            /^Near=[0-9]+\r?\n/.test(content) &&
            /^HTMLFirst=[01]\r?$/m.test(content) &&
            /^Cache=[01]\r?$/m.test(content))));
    if (metadata) inspection.kind = "mirror-metadata";
    if (file === "hts-log.txt" && metadata) {
      const hint = content.match(
        /^HTTrack[^\r\n]+ launched on ([A-Za-z]{3},? [0-9]{1,2} [A-Za-z]{3} [0-9]{4} [0-9:]{8}) at https?:\/\//,
      )?.[1];
      if (hint) inspection.mirrorTimestampHints = [hint];
    }
  }
  return { inspection, payload };
}
