git:
  repoRoot: "../.."
  paths:
    - packages/utils

grouping:
  period: week
  startDay: thu

languages:
  primary: en
  translations: []

ai:
  generation:
    provider: openai
  translation:
    provider: openai

output:
  dir: "."
  filename: CHANGELOG

sortOrder: desc
